org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Mapbox Downloads Token for native tile downloading
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoibW9vc2lhc2QiLCJhIjoiY20xdGRqNGRsMDFhNzJqcHlqNGRqNGRqNGRqIn0.example
