/// Canonical predefined place categories (English names in DB).
/// Used for DB seed, [placeCategoriesJson] alias, and i18n key resolution.
const Map<String, List<Map<String, String>>> kPlaceCategoriesSeed = {
  'Accommodation': [
    {'name': 'Home', 'emoji': '🏠'},
    {'name': 'Hotel', 'emoji': '🏨'},
    {'name': 'Motel', 'emoji': '🏩'},
    {'name': 'Hostel', 'emoji': '🛏️'},
    {'name': 'Bed and Breakfast', 'emoji': '🥞'},
    {'name': 'Vacation Rental', 'emoji': '🏡'},
    {'name': 'Campground', 'emoji': '🏕️'},
    {'name': 'Resort', 'emoji': '🏖️'},
    {'name': 'Guest House', 'emoji': '🏘️'},
  ],
  'Food and Drink': [
    {'name': 'Restaurant', 'emoji': '🍽️'},
    {'name': 'Cafe', 'emoji': '☕️'},
    {'name': 'Bar/Pub', 'emoji': '🍻'},
    {'name': 'Fast Food', 'emoji': '🍔'},
    {'name': 'Bakery', 'emoji': '🥖'},
    {'name': 'Food Court', 'emoji': '🥡'},
    {'name': 'Ice Cream Shop', 'emoji': '🍨'},
    {'name': 'Coffee Shop', 'emoji': '🫘'},
  ],
  'Retail and Shopping': [
    {'name': 'Supermarket', 'emoji': '🛒'},
    {'name': 'Convenience Store', 'emoji': '🏪'},
    {'name': 'Department Store', 'emoji': '🛍️'},
    {'name': 'Shopping Mall', 'emoji': '🏬'},
    {'name': 'Pharmacy', 'emoji': '💊'},
    {'name': 'Market', 'emoji': '🧺'},
    {'name': 'Jewelry Store', 'emoji': '💍'},
    {'name': 'Florist', 'emoji': '🌷'},
  ],
  'Health and Medical': [
    {'name': 'Hospital', 'emoji': '🏥'},
    {'name': 'Clinic', 'emoji': '🩺'},
    {'name': 'Pharmacy', 'emoji': '⚕️'},
    {'name': 'Dentist', 'emoji': '🦷'},
    {'name': 'Veterinary Clinic', 'emoji': '🐾'},
  ],
  'Education': [
    {'name': 'School', 'emoji': '🏫'},
    {'name': 'University', 'emoji': '🧑‍🎓'},
    {'name': 'College', 'emoji': '🎓'},
    {'name': 'Kindergarten', 'emoji': '🧒'},
    {'name': 'Library', 'emoji': '📚'},
  ],
  'Transportation': [
    {'name': 'Airport', 'emoji': '✈️'},
    {'name': 'Train Station', 'emoji': '🚆'},
    {'name': 'Bus Station', 'emoji': '🚍'},
    {'name': 'Subway/Metro Station', 'emoji': '🚇'},
    {'name': 'Taxi Stand', 'emoji': '🚖'},
    {'name': 'Parking Lot/Garage', 'emoji': '🅿️'},
    {'name': 'Bicycle Rental', 'emoji': '🚲'},
    {'name': 'Car Rental', 'emoji': '🚗'},
    {'name': 'Ferry Terminal', 'emoji': '⛴️'},
    {'name': 'Charging Station', 'emoji': '🔋'},
  ],
  'Financial Service': [
    {'name': 'Bank', 'emoji': '🏦'},
    {'name': 'ATM', 'emoji': '🏧'},
    {'name': 'Currency Exchange', 'emoji': '💱'},
    {'name': 'Insurance Agency', 'emoji': '📑'},
  ],
  'Entertainment and Recreation': [
    {'name': 'Movie Theater', 'emoji': '🎬'},
    {'name': 'Amusement Park', 'emoji': '🎡'},
    {'name': 'Zoo', 'emoji': '🐘'},
    {'name': 'Aquarium', 'emoji': '🐠'},
    {'name': 'Bowling Alley', 'emoji': '🎳'},
    {'name': 'Arcade', 'emoji': '🕹️'},
    {'name': 'Nightclub', 'emoji': '💃'},
    {'name': 'Casino', 'emoji': '♦️'},
    {'name': 'Concert Venue', 'emoji': '🎤'},
    {'name': 'Theater', 'emoji': '🎭'},
  ],
  'Cultural and Historical': [
    {'name': 'Museum', 'emoji': '🏛️'},
    {'name': 'Art Gallery', 'emoji': '🖼️'},
    {'name': 'Historical Site', 'emoji': '📜'},
    {'name': 'Monument', 'emoji': '🗿'},
    {'name': 'Archaeological Site', 'emoji': '⚒️'},
    {'name': 'Castle', 'emoji': '🏰'},
    {'name': 'Cultural Center', 'emoji': '🎎'},
    {'name': 'Memorial', 'emoji': '🪦'},
  ],
  'Sport and Fitness': [
    {'name': 'Gyms/Fitness Center', 'emoji': '🏋️'},
    {'name': 'Sports Field', 'emoji': '⚽️'},
    {'name': 'Stadium', 'emoji': '🏟️'},
    {'name': 'Swimming Pool', 'emoji': '🏊'},
    {'name': 'Golf Course', 'emoji': '⛳️'},
    {'name': 'Tennis Court', 'emoji': '🎾'},
    {'name': 'Skate Park', 'emoji': '🛹'},
    {'name': 'Yoga Studio', 'emoji': '🧘'},
  ],
  'Parks and Nature': [
    {'name': 'Park', 'emoji': '🌳'},
    {'name': 'Nature Reserve', 'emoji': '🌲'},
    {'name': 'Beach', 'emoji': '🏖️'},
    {'name': 'Forest', 'emoji': '🌴'},
    {'name': 'Coast', 'emoji': '🌊'},
    {'name': 'Botanical Garden', 'emoji': '🌺'},
    {'name': 'Picnic Area', 'emoji': '🧺'},
    {'name': 'Playground', 'emoji': '🛝'},
    {'name': 'Scenic Lookout', 'emoji': '🌄'},
  ],
  'Religious Site': [
    {'name': 'Church', 'emoji': '⛪️'},
    {'name': 'Mosque', 'emoji': '🕌'},
    {'name': 'Temple', 'emoji': '🛕'},
    {'name': 'Synagogue', 'emoji': '🕍'},
    {'name': 'Shrine', 'emoji': '🎐'},
    {'name': 'Monastery', 'emoji': '🏯'},
    {'name': 'Cemetery', 'emoji': '🪦'},
  ],
  'Government and Public Service': [
    {'name': 'Post Office', 'emoji': '📮'},
    {'name': 'Police Station', 'emoji': '👮'},
    {'name': 'Fire Station', 'emoji': '🚒'},
    {'name': 'Courthouse', 'emoji': '⚖️'},
    {'name': 'City Hall', 'emoji': '🏛️'},
    {'name': 'Embassy/Consulate', 'emoji': '🛂'},
    {'name': 'Public Library', 'emoji': '📖'},
    {'name': 'Community Center', 'emoji': '🏘️'},
  ],
  'Business and Professional Service': [
    {'name': 'Office', 'emoji': '🏢'},
    {'name': 'Co-working Space', 'emoji': '👩‍💻'},
    {'name': 'Conference Center', 'emoji': '🎤'},
    {'name': 'Law Firm', 'emoji': '⚖️'},
    {'name': 'Accounting Firm', 'emoji': '🧾'},
    {'name': 'Repair Shop', 'emoji': '🔧'},
  ],
  'Beauty and Personal Care': [
    {'name': 'Hair Salon', 'emoji': '💇'},
    {'name': 'Barbershop', 'emoji': '💈'},
    {'name': 'Spa', 'emoji': '💆'},
    {'name': 'Nail Salon', 'emoji': '💅'},
    {'name': 'Tattoo Parlor', 'emoji': '🎨'},
  ],
};
